### ISSUE TITLE
prrte: core dumps during a timeout when --get-stack-traces is enabled

### ISSUE THREAD

**Issue by AboorvaDevarajan** [openpmix/prrte#1367]
## Background information

```
ompi - master
26ff1684378e1c5859e377249a3e78f287b04216 3rd-party/openpmix (v1.1.3-3523-g26ff1684)
c1b9cacba9cb648164fbd9f4037ebf623acd70f9 3rd-party/prrte (psrvr-v2.0.0rc1-4356-gc1b9cacba9)
```

### Please describe the system on which you are running

* Operating system/version: RH8.5
* Computer hardware: x86_64
* Network type:

-----------------------------

## Details of the problem

prterun core dumps while printing the stack-trace when it hits the timeout.

```
$ cat hello_world.c 
#include <stdlib.h>
#include <stdio.h>
#include <mpi.h>

int
main(int argc, char *argv[])
{
	int		rank, size, len;
	char            name[MPI_MAX_PROCESSOR_NAME];
	
	MPI_Init(&argc, &argv);
	MPI_Comm_rank(MPI_COMM_WORLD, &rank);
	MPI_Comm_size(MPI_COMM_WORLD, &size);
	sleep(10);
	MPI_Get_processor_name(name, &len);
	printf ("Hello world! I'm %d of %d on %s\n", rank, size, name);

	MPI_Finalize();
	exit(0);
}
```

```
[prrte]$ mpicc hello_world.c -o hw

[prrte]$ mpirun --get-stack-traces --timeout 2 -np 2 --host f8n04:1,f8n05:1  ./hw
--------------------------------------------------------------------------
PMIx was unable to find a usable compression library
on the system. We will therefore be unable to compress
large data streams. This may result in longer-than-normal
startup times and larger memory footprints. We will
continue, but strongly recommend installing zlib or
a comparable compression library for better user experience.

You can suppress this warning by adding "pcompress_base_silence_warning=1"
to your PMIx MCA default parameter file, or by adding
"PMIX_MCA_pcompress_base_silence_warning=1" to your environment.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
The user-provided time limit for job execution has been reached:

  Timeout: 2 seconds

The job will now be aborted.  Please check your code and/or
adjust/remove the job execution time limit (as specified by --timeout
command line option or MPIEXEC_TIMEOUT environment variable).
--------------------------------------------------------------------------
Waiting for stack traces (this may take a few moments)...
free(): invalid pointer
Aborted (core dumped)

```

**Comment by AboorvaDevarajan** [comment]
This is a probable fix: https://github.com/openpmix/prrte/pull/1368

**Comment by AboorvaDevarajan** [comment]
Here is a probable fix: https://github.com/openpmix/prrte/pull/1368

**Comment by AboorvaDevarajan** [comment]
With patch:

```
[ prrte]$ mpirun --get-stack-traces --timeout 2 -np 2 --host f8n04:1,f8n05:1  ./hw
--------------------------------------------------------------------------
PMIx was unable to find a usable compression library
on the system. We will therefore be unable to compress
large data streams. This may result in longer-than-normal
startup times and larger memory footprints. We will
continue, but strongly recommend installing zlib or
a comparable compression library for better user experience.

You can suppress this warning by adding "pcompress_base_silence_warning=1"
to your PMIx MCA default parameter file, or by adding
"PMIX_MCA_pcompress_base_silence_warning=1" to your environment.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
The user-provided time limit for job execution has been reached:

  Timeout: 2 seconds

The job will now be aborted.  Please check your code and/or
adjust/remove the job execution time limit (as specified by --timeout
command line option or MPIEXEC_TIMEOUT environment variable).
--------------------------------------------------------------------------
Waiting for stack traces (this may take a few moments)...
STACK TRACE FOR PROC [prterun-c656f8mgt01-3434341@1,1] (f8n05, PID 3913381)
	Thread 2 (Thread 0x7fe344f9a700 (LWP 3913382)):
	#0  0x00007fe3470281b7 in epoll_wait () from /lib64/libc.so.6
	#1  0x00007fe3460a04a9 in epoll_dispatch () from /lib64/libevent_core-2.1.so.6
	#2  0x00007fe346096188 in event_base_loop () from /lib64/libevent_core-2.1.so.6
	#3  0x00007fe3465c463d in progress_engine (obj=0x250be40) at runtime/pmix_progress_threads.c:228
	#4  0x00007fe3472f62de in start_thread () from /lib64/libpthread.so.0
	#5  0x00007fe347027e83 in clone () from /lib64/libc.so.6
	Thread 1 (Thread 0x7fe347da2fc0 (LWP 3913381)):
	#0  0x00007fe346ff4238 in nanosleep () from /lib64/libc.so.6
	#1  0x00007fe346ff413e in sleep () from /lib64/libc.so.6
	#2  0x0000000000400918 in main ()
STACK TRACE FOR PROC [prterun-c656f8mgt01-3434341@1,0] (f8n04, PID 3127001)
	Thread 2 (Thread 0x7fda94175700 (LWP 3127002)):
	#0  0x00007fda962031b7 in epoll_wait () from /lib64/libc.so.6
	#1  0x00007fda9527b4a9 in epoll_dispatch () from /lib64/libevent_core-2.1.so.6
	#2  0x00007fda95271188 in event_base_loop () from /lib64/libevent_core-2.1.so.6
	#3  0x00007fda9579f63d in progress_engine (obj=0x200be40) at runtime/pmix_progress_threads.c:228
	#4  0x00007fda964d12de in start_thread () from /lib64/libpthread.so.0
	#5  0x00007fda96202e83 in clone () from /lib64/libc.so.6
	Thread 1 (Thread 0x7fda96f7bfc0 (LWP 3127001)):
	#0  0x00007fda961cf238 in nanosleep () from /lib64/libc.so.6
	#1  0x00007fda961cf13e in sleep () from /lib64/libc.so.6
	#2  0x0000000000400918 in main ()
```

**Comment by rhc54** [comment]
All committed - thanks!
