### ISSUE TITLE
Cleanup NULL hwloc topology segfault prterun

### ISSUE THREAD

**Issue by abouteiller** [openpmix/prrte#1624]
### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)

```
 git submodule
+acb07f24fdce5ab77ef676c65da11aadfa312b9b 3rd-party/openpmix (v1.1.3-3725-gacb07f24)
+d6134392271293b42337896587b6a7f4c17edf20 3rd-party/prrte (psrvr-v2.0.0rc1-4536-gd6134392)


d6134392 (HEAD -> master, origin/master, origin/HEAD) Cleanup a couple of things                                       Ralph Castain   2 days ago
```

I have not tested prte 3.0.1rc yet, but it may also be present there given the git log. 

### Please describe the system on which you are running

* Operating system/version: CentOS/7
* Computer hardware: x86_64
* Network type: ib10g

**The headnote has a different hardware topology than the compute nodes (that is probably relevant to the bug).**

-----------------------------

## Details of the problem

`mpiexec/prterun` crashes on launch of any job, because the PLM sends a NULL hwloc topology for deallocation. This may be related to the headnode having a different architecture than the compute node. 

```
 salloc -N 2 -Ccauchy  gdb --args ~/ompi/v5.0.x/build/bin/mpiexec -N 8 --map-by :oversubscribe --with-ft no --mca plm_base_verbose 100 --verbose --leave-session-attached  --mca dvm_base_verbose 100 --mca state_base_verbose 100  hostname
salloc: Nodes c[00-01] are ready for job
...
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] plm:slurm: launching on nodes c00,c01
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] plm:slurm: Set prefix:/home/bouteill/ompi/v5.0.x/build
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] plm:slurm: final top-level argv:
        srun --ntasks-per-node=1 --kill-on-bad-exit --mpi=none --cpu-bind=none --ntasks=2 prted --leave-session-attached --prtemca ess "slurm" --prtemca ess_base_nspace "prterun-saturn-7301@0" --prtemca ess_base_vpid "1" --prtemca ess_base_num_procs "3" --prtemca prte_hnp_uri "prterun-saturn-7301@0.0;tcp://160.36.131.133,10.0.0.1,10.1.0.1,192.168.122.1:39562:24,15,15,24" --prtemca plm_base_verbose "100" --prtemca state_base_verbose "100" --prtemca errmgr_base_verbose "00" --prtemca pmix_session_server "1"
...
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] plm:base:orted_report_launch from daemon [prterun-saturn-7301@0,2] on node c01
...
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] RECEIVED TOPOLOGY SIG 2N:2S:0L3:0L2:0L1:8C:8H:0-7::x86_64:le FROM NODE c01
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] NEW TOPOLOGY - ADDING SIGNATURE
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] CACHING DAEMON [prterun-saturn-7301@0,2]
...
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] plm:base:orted_report_launch from daemon [prterun-saturn-7301@0,1] on node c00
[saturn.icl.utk.edu:07301] [prterun-saturn-7301@0,0] RECEIVED TOPOLOGY SIG 2N:2S:0L3:0L2:0L1:8C:8H:0-7::x86_64:le FROM NODE c00

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6541729 in hwloc_backends_disable_all () from /lib64/libhwloc.so.5

(gdb) bt
#0  0x00007ffff6541729 in hwloc_backends_disable_all () from /lib64/libhwloc.so.5
#1  0x00007ffff653a419 in hwloc_topology_destroy () from /lib64/libhwloc.so.5
#2  0x00007ffff751551a in pmix_hwloc_destruct_topology (src=0x7fffffff8840) at ../../../../3rd-party/openpmix/src/hwloc/pmix_hwloc_datatype.c:492
#3  0x00007ffff766528d in pmix_bfrops_base_tma_topology_destruct (t=0x7fffffff8840, tma=0x0)
    at /home/bouteill/ompi/v5.0.x/3rd-party/openpmix/src/mca/bfrops/base/bfrop_base_tma.h:917
#4  0x00007ffff766e641 in PMIx_Topology_destruct (t=0x7fffffff8840) at ../../../../../../3rd-party/openpmix/src/mca/bfrops/base/bfrop_base_macro_backers.c:317
#5  0x00007ffff7b05471 in prte_plm_base_daemon_callback (status=0, sender=0x7a91a8, buffer=0x7a92d0, tag=10, cbdata=0x0)
    at ../../../../../../3rd-party/prrte/src/mca/plm/base/plm_base_launch_support.c:1544
#6  0x00007ffff7a84146 in prte_rml_base_process_msg (fd=-1, flags=4, cbdata=0x7a9080) at ../../../../3rd-party/prrte/src/rml/rml_base_msg_handlers.c:201
#7  0x00007ffff6988bd5 in event_process_active_single_queue (base=base@entry=0x64a7a0, activeq=0x64ada0, max_to_process=max_to_process@entry=2147483647,
    endtime=endtime@entry=0x0) at event.c:1691
#8  0x00007ffff69893ef in event_process_active (base=0x64a7a0) at event.c:1783
#9  event_base_loop (base=0x64a7a0, flags=1) at event.c:2006
#10 0x00000000004068f1 in main (argc=31, argv=0x7fffffff9798) at ../../../../../../3rd-party/prrte/src/tools/prte/prte.c:805

#5  0x00007ffff7b05471 in prte_plm_base_daemon_callback (status=0, sender=0x7a91a8, buffer=0x7a92d0, tag=10, cbdata=0x0)
    at ../../../../../../3rd-party/prrte/src/mca/plm/base/plm_base_launch_support.c:1544
1544                    PMIX_TOPOLOGY_DESTRUCT(&ptopo);
(gdb) list
1539                        prted_failed_launch = true;
1540                        goto CLEANUP;
1541                    }
1542                    topo = ptopo.topology;
1543                    ptopo.topology = NULL;
1544                    PMIX_TOPOLOGY_DESTRUCT(&ptopo);
1545                    /* cleanup */
1546                    PMIX_DATA_BUFFER_DESTRUCT(data);
1547                }
1548            }
(gdb) down
#4  0x00007ffff766e641 in PMIx_Topology_destruct (t=0x7fffffff8840) at ../../../../../../3rd-party/openpmix/src/mca/bfrops/base/bfrop_base_macro_backers.c:317
317         pmix_bfrops_base_tma_topology_destruct(t, NULL);
(gdb) down
#3  0x00007ffff766528d in pmix_bfrops_base_tma_topology_destruct (t=0x7fffffff8840, tma=0x0)
    at /home/bouteill/ompi/v5.0.x/3rd-party/openpmix/src/mca/bfrops/base/bfrop_base_tma.h:917
917         pmix_hwloc_destruct_topology(t);
(gdb) list
912         pmix_topology_t *t,
913         pmix_tma_t *tma
914     ) {
915         PMIX_HIDE_UNUSED_PARAMS(tma);
916         // TODO(skg)
917         pmix_hwloc_destruct_topology(t);
918     }
919
920     static inline pmix_topology_t *
921     pmix_bfrops_base_tma_topology_create(
(gdb) p *t
$3 = {source = 0x7ca280 "hwloc", topology = 0x0}
(gdb) down
#2  0x00007ffff751551a in pmix_hwloc_destruct_topology (src=0x7fffffff8840) at ../../../../3rd-party/openpmix/src/hwloc/pmix_hwloc_datatype.c:492
492         hwloc_topology_destroy(src->topology);
```

**Comment by abouteiller** [comment]
bug confirmed present also in v3.0.1rc1

**Comment by rhc54** [comment]
Actually isn't anything to do with PRRTE - it is a difference between PMIx v4.2.2 and v4.2.3 due to the macro-to-function conversion (which is why they didn't see it - they tested against the earlier version of PMIx). I fixed it in the referenced PR and will backport to the v4.2.3 release.
