### ISSUE TITLE
Proctable query segfaulting (for indirect tool launch use case)

### ISSUE THREAD

**Issue by dirk-schubert-arm** [openpmix/prrte#515]
### What version of the PMIx Reference Server / PMIx are you using?

Latest master.

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.04
* Computer hardware: x86-64

-----------------------------

## Details of the problem

Steps to reproduce:

```
# symlink mpirun to prte - for example with:
$ (cd $(dirname $(which prte)) && ln -s prte mpirun)
$ ./src/mpir mpirun -n 2 $X_PMIX_PATH/examples/hello
Segmentation fault (core dumped)
```

When run under GDB it looks like it's the proctable query which triggers the segfault:

```
mpir-shim$ gdb -ex "run" -ex "bt" --ex "frame 1" --ex "print *queries[0].keys" --args ./src/mpir mpirun -n 2 $X_PMIX_PATH/examples/hello
...
Thread 5 "mpir" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3614700 (LWP 14610)]
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x00007ffff21e4bfc in query (queries=0x7fffffffcf40, nqueries=1, results=0x7ffff36139e0, cbfunc=0x7ffff7b71780 <qcbfunc>, cbdata=0x7fffec002ea0) at pstrg_lustre.c:141
#2  0x00007ffff7b71cbb in pmix_pstrg_base_query (queries=0x7fffffffcf40, nqueries=1, results=0x7ffff36139e0, cbfunc=0x7ffff7b0aecc <nxtcbfunc>, cbdata=0x6984c0)
    at base/pstrg_base_stubs.c:95
#3  0x00007ffff7b0bb09 in localquery (sd=-1, args=4, cbdata=0x6984c0) at common/pmix_query.c:348
#4  0x00007ffff698b595 in event_process_active_single_queue (base=base@entry=0x645590, activeq=0x6459c0, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0)
    at event.c:1697
#5  0x00007ffff698bdaf in event_process_active (base=0x645590) at event.c:1789
#6  event_base_loop (base=0x645590, flags=1) at event.c:2012
#7  0x00007ffff7afb13f in progress_engine (obj=0x645460) at runtime/pmix_progress_threads.c:232
#8  0x00007ffff61006ba in start_thread (arg=0x7ffff3614700) at pthread_create.c:333
#9  0x00007ffff6ec841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
#1  0x00007ffff21e4bfc in query (queries=0x7fffffffcf40, nqueries=1, results=0x7ffff36139e0, cbfunc=0x7ffff7b71780 <qcbfunc>, cbdata=0x7fffec002ea0) at pstrg_lustre.c:141
141	            if (0 == strcmp(queries[n].qualifiers[m].key, PMIX_STORAGE_TYPE)) {
$1 = 0x69a5b0 "pmix.qry.ptable"
```

Please note that I am reporting the bug against PRRTE, but it could also be a problem in PMIx or the MPIR-shim (although I can trigger the same bug independent of the MPIR-shim).

**Comment by dirk-schubert-arm** [comment]
@rhc54: Can you have a look?

**Comment by dirk-schubert-arm** [comment]
Hey @rhc54,

Thanks for fixing this issue (and the other issues as well).

When I try the fix, the mpir-shim gets further, but reports the following new error:

```
FATAL ERROR: PMIx proc table info/ninfo is 0
```

Can you take a look? 

Thanks,
Dirk

**Comment by rhc54** [comment]
Sorry for delay - got snagged by something else. I can replicate, so let me fix this today.

**Comment by rhc54** [comment]
@dirk-schubert-arm Okay, I verified this is now working completely again.

**Comment by dirk-schubert-arm** [comment]
Cheers @rhc54, can confirm it works with latest master of both OpenPMIx and PRRTE.
